name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install homeassistant
          pip install pylint

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

      - name: Lint
        run: |
          pylint custom_components/luba_manager || true