name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          cd custom_components/luba_manager
          zip -r luba_manager.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: custom_components/luba_manager/luba_manager.zip